# Generated by scripts/update-cask.py from a published arm64 release.
cask "copilot-bridge-menubar" do
  version "0.2.0"
  sha256 "d6674e8668f2d3b5e9a8356e40a5994fd20f5f94bbe22bc31509e2acd32d4c60"

  url "https://github.com/hyspace/copilot-bridge-menubar/releases/download/v#{version}/Copilot-Bridge-arm64.zip"
  name "Copilot Bridge"
  desc "Native Apple Silicon menu-bar supervisor for Copilot Bridge"
  homepage "https://github.com/hyspace/copilot-bridge-menubar"

  depends_on arch: :arm64
  depends_on macos: ">= :sonoma"

  app "Copilot Bridge.app"
end
