# Generated by scripts/update-cask.py from a published arm64 release.
cask "copilot-bridge-menubar" do
  version "0.3.0"
  sha256 "a0eb01b15b8babcbb894f0d2ed84f59cc0c95fd133b7b683f85cab450235af43"

  url "https://github.com/hyspace/copilot-bridge-menubar/releases/download/v#{version}/Copilot-Bridge-arm64.zip"
  name "Copilot Bridge"
  desc "Native Apple Silicon menu-bar supervisor for Copilot Bridge"
  homepage "https://github.com/hyspace/copilot-bridge-menubar"

  depends_on arch: :arm64
  depends_on macos: :sonoma

  app "Copilot Bridge.app"
end
