# Generated by scripts/update-cask.py from a published arm64 release.
cask "copilot-bridge-menubar" do
  version "0.3.2"
  sha256 "1f3e4a5b975ea784a14ac626c441541388c867006163ec761cab8ae2dc6d68c3"

  url "https://github.com/hyspace/copilot-bridge-menubar/releases/download/v#{version}/Copilot-Bridge-arm64.zip"
  name "Copilot Bridge"
  desc "Native Apple Silicon menu-bar supervisor for Copilot Bridge"
  homepage "https://github.com/hyspace/copilot-bridge-menubar"

  depends_on arch: :arm64
  depends_on macos: :sonoma

  app "Copilot Bridge.app"
end
