# Generated by scripts/update-formula.py from a published arm64 release.
class CopilotBridgeMenubar < Formula
  desc "Native Apple Silicon menu-bar supervisor for Copilot Bridge"
  homepage "https://github.com/hyspace/copilot-bridge-menubar"
  url "https://github.com/hyspace/copilot-bridge-menubar/releases/download/v0.1.0/Copilot-Bridge-arm64.zip"
  version "0.1.0"
  revision 1
  sha256 "8b04ee69533bebe18259f85e6b2e3d09b576c386fc0e54163fb604def19a19e8"
  license "MIT"

  depends_on arch: :arm64
  depends_on macos: :sonoma
  skip_clean "libexec/Copilot Bridge.app"

  def install
    if (buildpath/"Copilot Bridge.app").directory?
      libexec.install "Copilot Bridge.app"
    elsif (buildpath/"Contents/Info.plist").file?
      # Some archive strategies enter the archive's only top-level directory.
      (libexec/"Copilot Bridge.app").mkpath
      # Homebrew may add staging metadata beside Contents. It is not signed app content.
      (libexec/"Copilot Bridge.app").install "Contents"
    else
      odie "Release archive does not contain Copilot Bridge.app"
    end
    bin.mkpath
    (bin/"copilot-bridge-menubar").write <<~SH
      #!/bin/bash
      set -euo pipefail
      APP="#{opt_libexec}/Copilot Bridge.app"
      case "${1:-}" in
        --version) exec "$APP/Contents/MacOS/CopilotBridgeMenuBar" --version ;;
        --foreground) exec "$APP/Contents/MacOS/CopilotBridgeMenuBar" --start-service ;;
        "") exec /usr/bin/open "$APP" ;;
        *) echo "Usage: copilot-bridge-menubar [--version|--foreground]" >&2; exit 2 ;;
      esac
    SH
    (bin/"copilot-bridge-menubar").chmod 0755
  end

  service do
    run [opt_bin/"copilot-bridge-menubar", "--foreground"]
    keep_alive false
    process_type :interactive
    working_dir var
    log_path var/"log/copilot-bridge-menubar.log"
    error_log_path var/"log/copilot-bridge-menubar-error.log"
  end

  def caveats
    <<~EOS
      Start the menu-bar app: copilot-bridge-menubar
      No existing CLI is stopped and no Codex configuration is rewritten.
      Use the app login item OR brew services, not both.
      The bundled app is ad-hoc signed unless the release explicitly says otherwise.
    EOS
  end

  test do
    assert_equal ["Contents"], (libexec/"Copilot Bridge.app").children.map { |path| path.basename.to_s }.sort
    assert_match version.to_s, shell_output("#{bin}/copilot-bridge-menubar --version")
    assert_predicate libexec/"Copilot Bridge.app/Contents/Resources/copilot-bridge-service", :executable?
    system "/usr/bin/codesign", "--verify", "--deep", "--strict", libexec/"Copilot Bridge.app"
  end
end
