#!/usr/bin/env python3
"""Generate a formula from a verified release archive checksum, never a guessed SHA."""
import argparse, pathlib, re
p=argparse.ArgumentParser()
p.add_argument("--version",required=True)
p.add_argument("--sha256",required=True)
p.add_argument("--repository",default="hyspace/copilot-bridge-menubar")
a=p.parse_args()
assert re.fullmatch(r"\d+\.\d+\.\d+",a.version), "Invalid release version"
assert re.fullmatch(r"[a-f0-9]{64}",a.sha256), "Invalid SHA256"
assert re.fullmatch(r"[A-Za-z0-9_.-]+/[A-Za-z0-9_.-]+",a.repository), "Invalid repository"
root=pathlib.Path(__file__).resolve().parent.parent
formula=root/"Formula/copilot-bridge-menubar.rb"
if formula.exists():
    match=re.search(r'  version "(\d+\.\d+\.\d+)"',formula.read_text())
    if match: assert tuple(map(int,a.version.split("."))) >= tuple(map(int,match[1].split("."))), "Refusing formula downgrade"
formula.parent.mkdir(exist_ok=True)
formula.write_text(f'''# Generated by scripts/update-formula.py from a published arm64 release.
class CopilotBridgeMenubar < Formula
  desc "Native Apple Silicon menu-bar supervisor for Copilot Bridge"
  homepage "https://github.com/{a.repository}"
  url "https://github.com/{a.repository}/releases/download/v{a.version}/Copilot-Bridge-arm64.zip"
  version "{a.version}"
  sha256 "{a.sha256}"
  license "MIT"

  depends_on arch: :arm64
  depends_on macos: :sonoma

  def install
    libexec.install "Copilot Bridge.app"
    (bin/"copilot-bridge-menubar").write <<~SH
      #!/bin/bash
      set -euo pipefail
      APP="#{{opt_libexec}}/Copilot Bridge.app"
      case "${{1:-}}" in
        --version) exec "$APP/Contents/MacOS/CopilotBridgeMenuBar" --version ;;
        --foreground) exec "$APP/Contents/MacOS/CopilotBridgeMenuBar" --start-service ;;
        "") exec /usr/bin/open "$APP" ;;
        *) echo "Usage: copilot-bridge-menubar [--version|--foreground]" >&2; exit 2 ;;
      esac
    SH
  end

  service do
    run [opt_bin/"copilot-bridge-menubar", "--foreground"]
    keep_alive false
    process_type :interactive
    working_dir var
    log_path var/"log/copilot-bridge-menubar.log"
    error_log_path var/"log/copilot-bridge-menubar-error.log"
  end

  def caveats
    <<~EOS
      Start the menu-bar app: copilot-bridge-menubar
      No existing CLI is stopped and no Codex configuration is rewritten.
      Use the app login item OR brew services, not both.
      The bundled app is ad-hoc signed unless the release explicitly says otherwise.
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{{bin}}/copilot-bridge-menubar --version")
    assert_predicate libexec/"Copilot Bridge.app/Contents/Resources/copilot-bridge-service", :executable?
    system "/usr/bin/codesign", "--verify", "--deep", "--strict", libexec/"Copilot Bridge.app"
  end
end
''')
print(formula)
