#!/usr/bin/env python3
"""Update the Homebrew package using a published release's verified checksum."""

import argparse
import os
from pathlib import Path
import re
import tempfile


def require(condition, message):
    if not condition:
        raise SystemExit(message)


parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument("--version", required=True)
parser.add_argument("--sha256", required=True)
parser.add_argument("--repository", default="hyspace/copilot-bridge-menubar")
args = parser.parse_args()

require(re.fullmatch(r"(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)", args.version),
        "Invalid release version")
require(re.fullmatch(r"[a-f0-9]{64}", args.sha256), "Invalid SHA256")
require(re.fullmatch(r"[A-Za-z0-9][A-Za-z0-9_.-]*/[A-Za-z0-9][A-Za-z0-9_.-]*",
                     args.repository), "Invalid repository")

root = Path(__file__).resolve().parent.parent
destination = root / "Casks/copilot-bridge-menubar.rb"
if destination.exists():
    current = destination.read_text()
    old_version = re.search(r'^  version "(\d+\.\d+\.\d+)"$', current, re.M)
    old_sha = re.search(r'^  sha256 "([a-f0-9]{64})"$', current, re.M)
    require(old_version and old_sha, "Existing package metadata is invalid")
    require(tuple(map(int, args.version.split("."))) >=
            tuple(map(int, old_version[1].split("."))), "Refusing version downgrade")
    if args.version == old_version[1]:
        require(args.sha256 == old_sha[1], "Refusing to change a published release checksum")

content = f'''# Generated by scripts/update-cask.py from a published arm64 release.
cask "copilot-bridge-menubar" do
  version "{args.version}"
  sha256 "{args.sha256}"

  url "https://github.com/{args.repository}/releases/download/v#{{version}}/Copilot-Bridge-arm64.zip"
  name "Copilot Bridge"
  desc "Native Apple Silicon menu-bar supervisor for Copilot Bridge"
  homepage "https://github.com/{args.repository}"

  depends_on arch: :arm64
  depends_on macos: :sonoma

  app "Copilot Bridge.app"
end
'''

destination.parent.mkdir(exist_ok=True)
temporary = None
try:
    with tempfile.NamedTemporaryFile(mode="w", encoding="utf-8", dir=destination.parent,
                                     prefix=".copilot-bridge-", suffix=".tmp",
                                     delete=False) as output:
        temporary = Path(output.name)
        output.write(content)
    temporary.chmod(0o644)
    os.replace(temporary, destination)
finally:
    if temporary is not None:
        temporary.unlink(missing_ok=True)
print(destination)
