#!/usr/bin/env python3
"""Generate a formula from a verified release archive checksum, never a guessed SHA."""
import argparse, pathlib, re
p=argparse.ArgumentParser()
p.add_argument("--version",required=True)
p.add_argument("--sha256",required=True)
p.add_argument("--repository",default="hyspace/copilot-bridge-menubar")
p.add_argument("--revision",type=int,default=0)
a=p.parse_args()
def require(condition, message):
    if not condition: raise SystemExit(message)
require(re.fullmatch(r"\d+\.\d+\.\d+",a.version), "Invalid release version")
require(re.fullmatch(r"[a-f0-9]{64}",a.sha256), "Invalid SHA256")
require(re.fullmatch(r"[A-Za-z0-9_.-]+/[A-Za-z0-9_.-]+",a.repository), "Invalid repository")
require(a.revision >= 0, "Invalid revision")
root=pathlib.Path(__file__).resolve().parent.parent
formula=root/"Formula/copilot-bridge-menubar.rb"
if formula.exists():
    match=re.search(r'  version "(\d+\.\d+\.\d+)"',formula.read_text())
    if match:
        require(tuple(map(int,a.version.split("."))) >= tuple(map(int,match[1].split("."))), "Refusing formula downgrade")
        if a.version == match[1]:
            old_revision = re.search(r"^  revision (\d+)$", formula.read_text(), re.M)
            require(a.revision >= (int(old_revision[1]) if old_revision else 0), "Refusing formula revision downgrade")
formula.parent.mkdir(exist_ok=True)
formula.write_text(f'''# Generated by scripts/update-formula.py from a published arm64 release.
class CopilotBridgeMenubar < Formula
  desc "Native Apple Silicon menu-bar supervisor for Copilot Bridge"
  homepage "https://github.com/{a.repository}"
  url "https://github.com/{a.repository}/releases/download/v{a.version}/Copilot-Bridge-arm64.zip"
  version "{a.version}"
{f"  revision {a.revision}" if a.revision else ""}
  sha256 "{a.sha256}"
  license "MIT"

  depends_on arch: :arm64
  depends_on macos: :sonoma
  skip_clean "libexec/Copilot Bridge.app"

  def install
    if (buildpath/"Copilot Bridge.app").directory?
      libexec.install "Copilot Bridge.app"
    elsif (buildpath/"Contents/Info.plist").file?
      # Some archive strategies enter the archive's only top-level directory.
      (libexec/"Copilot Bridge.app").mkpath
      # Homebrew may add staging metadata beside Contents. It is not signed app content.
      (libexec/"Copilot Bridge.app").install "Contents"
    else
      odie "Release archive does not contain Copilot Bridge.app"
    end
    bin.mkpath
    (bin/"copilot-bridge-menubar").write <<~SH
      #!/bin/bash
      set -euo pipefail
      APP="#{{opt_libexec}}/Copilot Bridge.app"
      case "${{1:-}}" in
        --version) exec "$APP/Contents/MacOS/CopilotBridgeMenuBar" --version ;;
        --foreground) exec "$APP/Contents/MacOS/CopilotBridgeMenuBar" --start-service ;;
        "") exec /usr/bin/open "$APP" ;;
        *) echo "Usage: copilot-bridge-menubar [--version|--foreground]" >&2; exit 2 ;;
      esac
    SH
    (bin/"copilot-bridge-menubar").chmod 0755
  end

  service do
    run [opt_bin/"copilot-bridge-menubar", "--foreground"]
    keep_alive false
    process_type :interactive
    working_dir var
    log_path var/"log/copilot-bridge-menubar.log"
    error_log_path var/"log/copilot-bridge-menubar-error.log"
  end

  def caveats
    <<~EOS
      Start the menu-bar app: copilot-bridge-menubar
      No existing CLI is stopped and no Codex configuration is rewritten.
      Use the app login item OR brew services, not both.
      The bundled app is ad-hoc signed unless the release explicitly says otherwise.
    EOS
  end

  test do
    assert_equal ["Contents"], (libexec/"Copilot Bridge.app").children.map {{ |path| path.basename.to_s }}.sort
    assert_match version.to_s, shell_output("#{{bin}}/copilot-bridge-menubar --version")
    assert_predicate libexec/"Copilot Bridge.app/Contents/Resources/copilot-bridge-service", :executable?
    system "/usr/bin/codesign", "--verify", "--deep", "--strict", libexec/"Copilot Bridge.app"
  end
end
''')
print(formula)
